/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      get_pairs: {
        [k: string]: unknown;
      };
    }
  | {
      get_time_trigger_ids: {
        [k: string]: unknown;
      };
    }
  | {
      get_trigger_id_by_fin_limit_order_idx: {
        order_idx: Uint128;
        [k: string]: unknown;
      };
    }
  | {
      get_vault: {
        address: string;
        vault_id: Uint128;
      };
    }
  | {
      get_vaults_by_address: {
        address: string;
        [k: string]: unknown;
      };
    }
  | {
      get_events_by_resource_id: {
        resource_id: Uint128;
        [k: string]: unknown;
      };
    }
  | {
      get_events: {
        limit?: number | null;
        start_after?: number | null;
        [k: string]: unknown;
      };
    };
/**
 * A thin wrapper around u128 that is using strings for JSON encoding/decoding, such that the full u128 range can be used for clients that convert JSON numbers to floats, like JavaScript and jq.
 *
 * # Examples
 *
 * Use `from` to create instances of this and `u128` to get the value out:
 *
 * ``` # use cosmwasm_std::Uint128; let a = Uint128::from(123u128); assert_eq!(a.u128(), 123);
 *
 * let b = Uint128::from(42u64); assert_eq!(b.u128(), 42);
 *
 * let c = Uint128::from(70u32); assert_eq!(c.u128(), 70); ```
 */
export type Uint128 = string;
