import { MainnetDenoms } from '@models/Denom';
import { DenomInfo } from './DenomInfo';

export const mainnetDenomsKujira: Record<MainnetDenoms, Partial<DenomInfo>> = {
  [MainnetDenoms.ATOM]: {
    name: 'ATOM',
    icon: '/images/denoms/atom.svg',
    stakeable: true,
    coingeckoId: 'cosmos',
    enabledInDcaPlus: true,
  },
  [MainnetDenoms.stATOM]: {
    name: 'stATOM',
    icon: '/images/denoms/statom.svg',
    stakeable: true,
    coingeckoId: 'stride-staked-atom',
    enabledInDcaPlus: true,
  },
  [MainnetDenoms.USK]: {
    name: 'USK',
    icon: '/images/denoms/usk.svg',
    stable: true,
    coingeckoId: 'usk',
  },
  [MainnetDenoms.Kuji]: {
    name: 'KUJI',
    icon: '/images/denoms/kuji.svg',
    coingeckoId: 'kujira',
    stakeable: true,
    stakeableAndSupported: true,
  },
  [MainnetDenoms.axlUSDC]: {
    name: 'axlUSDC',
    icon: '/images/denoms/usdc.svg',
    stable: true,
    coingeckoId: 'usd-coin',
  },
  [MainnetDenoms.WETH]: {
    name: 'wETH',
    icon: '/images/denoms/weth.svg',
    stakeable: true,
    coingeckoId: 'weth',
    significantFigures: 18,
    minimumSwapAmount: 0.05 / 1000,
    enabledInDcaPlus: true,
  },
  [MainnetDenoms.Stars]: {
    name: 'STARS',
    icon: '/images/denoms/stars.svg',
    stakeable: true,
    coingeckoId: 'stargaze',
  },
  [MainnetDenoms.SCRT]: {
    name: 'SCRT',
    icon: '/images/denoms/scrt.svg',
    stakeable: true,
    coingeckoId: 'secret',
    enabled: true,
  },
  [MainnetDenoms.LOCAL]: {
    name: 'LOCAL',
    icon: '/images/denoms/local.svg',
    stakeable: true,

    coingeckoId: 'local-money',
  },
  [MainnetDenoms.LUNA]: {
    name: 'LUNA',
    icon: '/images/denoms/luna.svg',
    stakeable: true,
    coingeckoId: 'terra-luna-2',
    enabled: true,
  },
  [MainnetDenoms.WBNB]: {
    name: 'wBNB',
    icon: '/images/denoms/wbnb.svg',
    stakeable: true,
    coingeckoId: 'binancecoin',
    minimumSwapAmount: 0.05 / 1000,
    significantFigures: 18,
    enabledInDcaPlus: true,
  },
  [MainnetDenoms.OSMO]: {
    name: 'OSMO',
    icon: '/images/denoms/osmo.svg',
    stakeable: true,
    coingeckoId: 'osmosis',
  },
  [MainnetDenoms.DOT]: {
    name: 'DOT',
    icon: '/images/denoms/dot.svg',
    stakeable: true,
    coingeckoId: 'polkadot',
    minimumSwapAmount: 0.05 / 1000,
    significantFigures: 10,
    enabledInDcaPlus: true,
  },
  [MainnetDenoms.GPAXG]: {
    name: 'gPAXG',
    icon: '/images/denoms/gpaxg.svg',
    stakeable: true,
    coingeckoId: 'pax-gold',
    significantFigures: 18,
    minimumSwapAmount: 0.05 / 1000,
  },
  [MainnetDenoms.MARS]: {
    name: 'MARS',
    icon: '/images/denoms/mars.svg',
    stakeable: true,
    coingeckoId: 'mars-protocol-a7fcbcfb-fd61-4017-92f0-7ee9f9cc6da3',
  },
  [MainnetDenoms.STRD]: {
    name: 'STRD',
    icon: '/images/denoms/strd.svg',
    stakeable: true,
    coingeckoId: 'stride',
  },
  [MainnetDenoms.JUNO]: {
    name: 'JUNO',
    icon: '/images/denoms/juno.png',
    stakeable: true,
    coingeckoId: 'juno-network',
  },
  [MainnetDenoms.wTAO]: {
    name: 'wTAO',
    icon: '/images/denoms/wtao.svg',
    stakeable: true,
    coingeckoId: 'wrapped-tao',
    significantFigures: 9,
  },
  [MainnetDenoms.INJ]: {
    name: 'INJ',
    icon: '/images/denoms/injective.png',
    stakeable: true,
    coingeckoId: 'injective-protocol',
    significantFigures: 18,
  },
  [MainnetDenoms.WHALE]: {
    name: 'WHALE',
    icon: '/images/denoms/whale.svg',
    stakeable: true,
    coingeckoId: 'white-whale',
  },
  [MainnetDenoms.ROAR]: {
    name: 'ROAR',
    icon: '/images/denoms/roar.svg',
    stakeable: true,
    coingeckoId: 'lion-dao',
    pricePrecision: 10,
  },
  [MainnetDenoms.AKT]: {
    name: 'AKT',
    icon: '/images/denoms/akt.svg',
    stakeable: true,
    coingeckoId: 'akash-network',
  },
  [MainnetDenoms.MNTA]: {
    name: 'MNTA',
    icon: '/images/denoms/mnta.png',
    stakeable: true,
    coingeckoId: 'mantadao',
    pricePrecision: 4,
  },
  [MainnetDenoms.ARB]: {
    name: 'ARB',
    icon: '/images/denoms/arb.svg',
    stakeable: true,
    coingeckoId: 'arbitrum',
    significantFigures: 18,
  },
  [MainnetDenoms.CNTO]: {
    name: 'CNTO',
    icon: '/images/denoms/cnto.png',
    stakeable: true,
    coingeckoId: 'ciento-exchange',
    significantFigures: 18,
  },
  [MainnetDenoms.ARCH]: {
    name: 'ARCH',
    icon: '/images/denoms/archway.svg',
    coingeckoId: 'archway',
    significantFigures: 18,
    pricePrecision: 4,
  },
  [MainnetDenoms.USDC]: {
    name: 'USDC',
    icon: '/images/denoms/usdc.svg',
    coingeckoId: 'usd-coin',
    stable: true,
  },
  [MainnetDenoms.wBTC]: {
    name: 'wBTC',
    icon: '/images/denoms/wbtc.png',
    coingeckoId: 'wrapped-bitcoin',
    significantFigures: 8,
    minimumSwapAmount: 0.05 / 10000,
  },
  [MainnetDenoms.WINK]: {
    name: 'WINK',
    icon: '/images/denoms/wink.png',
    coingeckoId: 'winkhub',
  },
  [MainnetDenoms.wstETH]: {
    name: 'wstETH',
    icon: '/images/denoms/wsteth.svg',
    coingeckoId: 'wrapped-steth',
    significantFigures: 18,
    pricePrecision: 2,
  },
  [MainnetDenoms.yieldETH]: {
    name: 'yieldETH',
    icon: '/images/denoms/yieldeth.svg',
    coingeckoId: 'yieldeth-sommelier',
    significantFigures: 18,
  },
  [MainnetDenoms.TIA]: {
    name: 'TIA',
    icon: '/images/denoms/tia.svg',
    coingeckoId: 'celestia',
  },
  [MainnetDenoms.FUZN]: {
    name: 'FUZN',
    icon: '/images/denoms/fuzn.svg',
    coingeckoId: 'fuzn',
  },
  [MainnetDenoms.nBTC]: {
    name: 'nBTC',
    icon: '/images/denoms/nbtc.svg',
    coingeckoId: 'bitcoin',
    enabledInDcaPlus: true,
    significantFigures: 14,
    minimumSwapAmount: 0.05 / 10000,
  },
  [MainnetDenoms.NSTK]: {
    name: 'NSTK',
    icon: '/images/denoms/nstk.svg',
    coingeckoId: 'unstake-fi',
  },
  [MainnetDenoms.PLNK]: {
    name: 'PLNK',
    icon: '/images/denoms/plnk.png',
    coingeckoId: 'unknown',
  },
  [MainnetDenoms.DYDX]: {
    name: 'DYDX',
    icon: '/images/denoms/dydx.png',
    coingeckoId: 'dydx-chain',
    significantFigures: 18,
  },
  [MainnetDenoms.ASTRO]: {
    name: 'ASTRO',
    icon: '/images/denoms/astro.png',
    coingeckoId: 'astroport-fi',
  },
  [MainnetDenoms.CRBRUS]: {
    name: 'CRBRUS',
    icon: '/images/denoms/crbrus.png',
    coingeckoId: 'cerberus',
  },
  [MainnetDenoms.RIO]: {
    name: 'RIO',
    icon: '/images/denoms/rio.png',
    coingeckoId: 'realio-network',
    significantFigures: 18,
  },
};
