import { MainnetDenoms } from '@models/Denom';
import { DenomInfo } from './DenomInfo';

export const mainnetDenomsKujira: Record<MainnetDenoms, Partial<DenomInfo>> = {
  [MainnetDenoms.ATOM]: {
    name: 'ATOM',
    icon: '/images/denoms/atom.svg',
    stakeable: true,
    coingeckoId: 'cosmos',
    significantFigures: 6,
    enabledInDcaPlus: true,
  },
  [MainnetDenoms.stATOM]: {
    name: 'stATOM',
    icon: '/images/denoms/statom.svg',
    stakeable: true,
    coingeckoId: 'stride-staked-atom',
    significantFigures: 6,
    enabledInDcaPlus: true,
  },
  [MainnetDenoms.USK]: {
    name: 'USK',
    icon: '/images/denoms/usk.svg',
    stakeable: false,
    stable: true,
    coingeckoId: 'usk',

    significantFigures: 6,
  },
  [MainnetDenoms.Kuji]: {
    name: 'KUJI',
    icon: '/images/denoms/kuji.svg',
    coingeckoId: 'kujira',
    stakeableAndSupported: true,
    significantFigures: 6,
  },
  [MainnetDenoms.axlUSDC]: {
    name: 'axlUSDC',
    icon: '/images/denoms/usdc.svg',
    stakeable: false,
    stable: true,
    coingeckoId: 'usd-coin',
    significantFigures: 6,
  },
  [MainnetDenoms.WETH]: {
    name: 'wETH',
    icon: '/images/denoms/weth.svg',
    stakeable: true,
    stable: false,
    coingeckoId: 'weth',
    conversion: (value: number) => value / 10 ** 18,
    deconversion: (value: number) => Math.round(value * 10 ** 18),
    significantFigures: 18,

    priceDeconversion: (value: number | undefined | null) => Number(value) * 10 ** 12,
    priceConversion: (value: number | undefined | null) => Number(value) / 10 ** 12,
    enabled: true,
    minimumSwapAmount: 0.05 / 1000,
    enabledInDcaPlus: true,
  },
  [MainnetDenoms.Stars]: {
    name: 'STARS',
    icon: '/images/denoms/stars.svg',
    stakeable: true,
    stable: false,
    coingeckoId: 'stargaze',
    enabled: true,
    significantFigures: 6,
  },
  [MainnetDenoms.SCRT]: {
    name: 'SCRT',
    icon: '/images/denoms/scrt.svg',
    stakeable: true,
    stable: false,
    coingeckoId: 'secret',
    enabled: true,
    significantFigures: 6,
  },
  [MainnetDenoms.LOCAL]: {
    name: 'LOCAL',
    icon: '/images/denoms/local.svg',
    stakeable: true,
    stable: false,
    coingeckoId: 'local-money',
    enabled: true,
    significantFigures: 6,
  },
  [MainnetDenoms.LUNA]: {
    name: 'LUNA',
    icon: '/images/denoms/luna.svg',
    stakeable: true,
    coingeckoId: 'terra-luna-2',
    enabled: true,
    significantFigures: 6,
  },
  [MainnetDenoms.WBNB]: {
    name: 'wBNB',
    icon: '/images/denoms/wbnb.svg',
    stakeable: true,
    stable: false,
    coingeckoId: 'binancecoin',
    enabled: true,
    conversion: (value: number) => value / 10 ** 18,
    deconversion: (value: number) => Math.round(value * 10 ** 18),
    priceDeconversion: (value: number | undefined | null) => Number(value) * 10 ** 12,
    priceConversion: (value: number | undefined | null) => Number(value) / 10 ** 12,
    minimumSwapAmount: 0.05 / 1000,
    significantFigures: 18,
    enabledInDcaPlus: true,
  },
  [MainnetDenoms.OSMO]: {
    name: 'OSMO',
    icon: '/images/denoms/osmo.svg',
    stakeable: true,
    stable: false,
    coingeckoId: 'osmosis',
    enabled: true,
    significantFigures: 6,
  },
  [MainnetDenoms.DOT]: {
    name: 'DOT',
    icon: '/images/denoms/dot.svg',
    stakeable: true,
    stable: false,
    coingeckoId: 'polkadot',
    enabled: true,
    conversion: (value: number) => value / 10 ** 10,
    deconversion: (value: number) => Math.round(value * 10 ** 10),
    priceDeconversion: (value: number | undefined | null) => Number(value) * 10 ** 4,
    priceConversion: (value: number | undefined | null) => Number(value) / 10 ** 4,
    minimumSwapAmount: 0.05 / 1000,
    significantFigures: 10,
    enabledInDcaPlus: true,
  },
  [MainnetDenoms.GPAXG]: {
    name: 'gPAXG',
    icon: '/images/denoms/gpaxg.svg',
    stakeable: true,
    stable: false,
    coingeckoId: 'pax-gold',
    enabled: true,
    conversion: (value: number) => value / 10 ** 18,
    deconversion: (value: number) => Math.round(value * 10 ** 18),
    priceDeconversion: (value: number | undefined | null) => Number(value) * 10 ** 12,
    priceConversion: (value: number | undefined | null) => Number(value) / 10 ** 12,
    significantFigures: 18,
    minimumSwapAmount: 0.05 / 1000,
  },
  [MainnetDenoms.MARS]: {
    name: 'MARS',
    icon: '/images/denoms/mars.svg',
    stakeable: true,
    stable: false,
    coingeckoId: 'mars-protocol-a7fcbcfb-fd61-4017-92f0-7ee9f9cc6da3',
    enabled: true,
    significantFigures: 6,
  },
  [MainnetDenoms.STRD]: {
    name: 'STRD',
    icon: '/images/denoms/strd.svg',
    stakeable: true,
    stable: false,
    coingeckoId: 'stride',
    enabled: true,
    significantFigures: 6,
  },
  [MainnetDenoms.JUNO]: {
    name: 'JUNO',
    icon: '/images/denoms/juno.png',
    stakeable: true,
    stable: false,
    coingeckoId: 'juno-network',
    enabled: true,
    significantFigures: 6,
  },
  [MainnetDenoms.wTAO]: {
    name: 'wTAO',
    icon: '/images/denoms/wtao.svg',
    stakeable: true,
    stable: false,
    coingeckoId: 'wrapped-tao',
    enabled: true,
    conversion: (value: number) => value / 10 ** 9,
    deconversion: (value: number) => Math.round(value * 10 ** 9),
    priceDeconversion: (value: number | undefined | null) => Number(value) * 10 ** 3,
    priceConversion: (value: number | undefined | null) => Number(value) / 10 ** 3,
    significantFigures: 9,
  },
  [MainnetDenoms.INJ]: {
    name: 'INJ',
    icon: '/images/denoms/injective.png',
    stakeable: true,
    stable: false,
    coingeckoId: 'injective-protocol',
    conversion: (value: number) => value / 10 ** 18,
    deconversion: (value: number) => Math.round(value * 10 ** 18),
    priceDeconversion: (value: number | undefined | null) => Number(value) * 10 ** 12,
    priceConversion: (value: number | undefined | null) => Number(value) / 10 ** 12,
    enabled: true,
    significantFigures: 18,
  },
  [MainnetDenoms.WHALE]: {
    name: 'WHALE',
    icon: '/images/denoms/whale.svg',
    stakeable: true,
    stable: false,
    coingeckoId: 'white-whale',
    enabled: true,
    significantFigures: 6,
  },
  [MainnetDenoms.ROAR]: {
    name: 'ROAR',
    icon: '/images/denoms/roar.svg',
    stakeable: true,
    coingeckoId: 'lion-dao',
    significantFigures: 6,
    enabledInDcaPlus: false,
    stable: false,
    pricePrecision: 10,
  },
  [MainnetDenoms.AKT]: {
    name: 'AKT',
    icon: '/images/denoms/akt.svg',
    stakeable: true,
    coingeckoId: 'akash-network',
    significantFigures: 6,
    enabledInDcaPlus: false,
    stable: false,
    pricePrecision: 3,
  },
  [MainnetDenoms.MNTA]: {
    name: 'MNTA',
    icon: '/images/denoms/mnta.png',
    stakeable: true,
    coingeckoId: 'mantadao',
    significantFigures: 6,
    enabledInDcaPlus: false,
    stable: false,
    pricePrecision: 4,
  },
  [MainnetDenoms.ARB]: {
    name: 'ARB',
    icon: '/images/denoms/arb.svg',
    stakeable: true,
    coingeckoId: 'arbitrum',
    conversion: (value: number) => value / 10 ** 18,
    deconversion: (value: number) => Math.round(value * 10 ** 18),
    significantFigures: 18,
    priceDeconversion: (value: number | undefined | null) => Number(value) * 10 ** 12,
    priceConversion: (value: number | undefined | null) => Number(value) / 10 ** 12,
    enabledInDcaPlus: false,
    stable: false,
    pricePrecision: 3,
  },
  [MainnetDenoms.CNTO]: {
    name: 'CNTO',
    icon: '/images/denoms/cnto.png',
    stakeable: true,
    coingeckoId: 'ciento-exchange',
    conversion: (value: number) => value / 10 ** 18,
    deconversion: (value: number) => Math.round(value * 10 ** 18),
    significantFigures: 18,
    priceDeconversion: (value: number | undefined | null) => Number(value) * 10 ** 12,
    priceConversion: (value: number | undefined | null) => Number(value) / 10 ** 12,
    enabledInDcaPlus: false,
    stable: false,
    pricePrecision: 3,
  },
  [MainnetDenoms.ARCH]: {
    name: 'ARCH',
    icon: '/images/denoms/archway.svg',
    stakeable: false,
    coingeckoId: 'archway',
    conversion: (value: number) => value / 10 ** 18,
    deconversion: (value: number) => Math.round(value * 10 ** 18),
    significantFigures: 18,
    priceDeconversion: (value: number | undefined | null) => Number(value) * 10 ** 12,
    priceConversion: (value: number | undefined | null) => Number(value) / 10 ** 12,
    enabledInDcaPlus: false,
    stable: false,
    pricePrecision: 4,
  },
  [MainnetDenoms.USDC]: {
    name: 'USDC',
    icon: '/images/denoms/usdc.svg',
    coingeckoId: 'usd-coin',
    stakeable: false,
    stable: true,
    enabled: true,
    significantFigures: 6,
  },
  [MainnetDenoms.wBTC]: {
    name: 'wBTC',
    icon: '/images/denoms/wbtc.png',
    coingeckoId: 'wrapped-bitcoin',
    stakeable: false,
    stable: false,
    enabled: true,
    conversion: (value: number) => value / 10 ** 8,
    deconversion: (value: number) => Math.round(value * 10 ** 8),
    significantFigures: 8,
    priceDeconversion: (value: number | undefined | null) => Number(value) * 10 ** 2,
    priceConversion: (value: number | undefined | null) => Number(value) / 10 ** 2,
    minimumSwapAmount: 0.05 / 10000,
  },
  [MainnetDenoms.WINK]: {
    name: 'WINK',
    icon: '/images/denoms/wink.png',
    coingeckoId: 'winkhub',
    stakeable: false,
    stable: false,
    enabled: true,
    significantFigures: 6,
  },
  [MainnetDenoms.wstETH]: {
    name: 'wstETH',
    icon: '/images/denoms/wsteth.svg',
    coingeckoId: 'wrapped-steth',
    stakeable: false,
    stable: false,
    enabled: true,
    conversion: (value: number) => value / 10 ** 18,
    deconversion: (value: number) => Math.round(value * 10 ** 18),
    significantFigures: 18,
    priceDeconversion: (value: number | undefined | null) => Number(value) * 10 ** 12,
    priceConversion: (value: number | undefined | null) => Number(value) / 10 ** 12,
    enabledInDcaPlus: false,
    pricePrecision: 2,
  },
  [MainnetDenoms.yeildETH]: {
    name: 'yeildETH',
    icon: '/images/denoms/yieldeth.svg',
    coingeckoId: 'yieldeth-sommelier',
    stakeable: false,
    stable: false,
    enabled: true,
    conversion: (value: number) => value / 10 ** 18,
    deconversion: (value: number) => Math.round(value * 10 ** 18),
    significantFigures: 18,
    priceDeconversion: (value: number | undefined | null) => Number(value) * 10 ** 12,
    priceConversion: (value: number | undefined | null) => Number(value) / 10 ** 12,
    enabledInDcaPlus: false,
    pricePrecision: 3,
  },
  [MainnetDenoms.TIA]: {
    name: 'TIA',
    icon: '/images/denoms/tia.svg',
    coingeckoId: 'celestia',
    stakeable: false,
    stable: false,
    enabled: true,
    significantFigures: 6,
  },
  [MainnetDenoms.FUZN]: {
    name: 'FUZN',
    icon: '/images/denoms/fuzn.svg',
    coingeckoId: 'fuzn',
    stakeable: false,
    stable: false,
    enabled: true,
    significantFigures: 6,
  },
  [MainnetDenoms.nBTC]: {
    name: 'nBTC',
    icon: '/images/denoms/nbtc.svg',
    coingeckoId: 'bitcoin',
    stakeable: false,
    stable: false,
    enabled: true,
    enabledInDcaPlus: true,
    conversion: (value: number) => value / 10 ** 14,
    deconversion: (value: number) => Math.round(value * 10 ** 14),
    significantFigures: 14,
    priceDeconversion: (value: number | undefined | null) => Number(value) * 10 ** 8,
    priceConversion: (value: number | undefined | null) => Number(value) / 10 ** 8,
    minimumSwapAmount: 0.05 / 10000,
  },
  [MainnetDenoms.NSTK]: {
    name: 'NSTK',
    icon: '/images/denoms/nstk.svg',
    coingeckoId: '',
    stakeable: false,
    stable: false,
    enabled: true,
    significantFigures: 6,
  },
};
