name: 'Deploy: Test'

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy-calc-fi-frontend-sandbox:
    name: Deploy
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      ENVIRONMENT: test
      BUCKET_DOMAIN_NAME: test.calculated.fi
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  e2e-calc-fi-frontend-production:
    name: E2E (production)
    uses: ./.github/workflows/cypress-production.yml
    needs: [deploy-calc-fi-frontend-sandbox]
