name: Deploy to Sandbox

on:
  push:
    branches:
      - main

jobs:
  test-calc-fi-frontend-sandbox:
    name: Test (sandbox)
    uses: ./.github/workflows/test.yml
    with:
      ENVIRONMENT: test
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CHAIN_ID: ${{ secrets.CHAIN_ID }}
      CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
      REST_ENDPOINT: ${{ secrets.REST_ENDPOINT }}
      RPC_ENDPOINT: ${{ secrets.RPC_ENDPOINT }}
      STAKING_ROUTER_CONTRACT_ADDRESS: ${{ secrets.STAKING_ROUTER_CONTRACT_ADDRESS }}
      FEE_TAKER_ADDRESS: ${{ secrets.FEE_TAKER_ADDRESS }}

  deploy-calc-fi-frontend-sandbox:
    name: Deploy (sandbox)
    uses: ./.github/workflows/deploy.yml
    needs:
      - test-calc-fi-frontend-sandbox
    with:
      ENVIRONMENT: test
      BUCKET_DOMAIN_NAME: test.calculated.fi
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CHAIN_ID: ${{ secrets.CHAIN_ID }}
      CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
      REST_ENDPOINT: ${{ secrets.REST_ENDPOINT }}
      RPC_ENDPOINT: ${{ secrets.RPC_ENDPOINT }}
      STAKING_ROUTER_CONTRACT_ADDRESS: ${{ secrets.STAKING_ROUTER_CONTRACT_ADDRESS }}
      FEE_TAKER_ADDRESS: ${{ secrets.FEE_TAKER_ADDRESS }}
      