name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-calc-fi-sandbox:
    name: Test (sandbox)
    uses: ./.github/workflows/test.yml
    with:
      ENVIRONMENT: test
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-calc-fi-sandbox:
    name: Deploy (sandbox)
    uses: ./.github/workflows/deploy.yml
    needs:
      - test-calc-fi-sandbox
    with:
      ENVIRONMENT: test
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
