name: Deploy to Production

on:
  push:
    branches:
      - release

jobs:
  test-calc-fi-frontend-sandbox:
    name: Test (sandbox)
    uses: ./.github/workflows/test.yml
    with:
      ENVIRONMENT: test
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-calc-fi-frontend-sandbox:
    name: Deploy (sandbox)
    uses: ./.github/workflows/deploy.yml
    needs:
      - test-calc-fi-frontend-sandbox
    with:
      ENVIRONMENT: test
      BUCKET_DOMAIN_NAME: test.calculated.fi
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-calc-fi-frontend-production:
    name: Deploy (production)
    uses: ./.github/workflows/deploy.yml
    needs: [test-calc-fi-frontend-sandbox, deploy-calc-fi-frontend-sandbox]
    with:
      ENVIRONMENT: production
      BUCKET_DOMAIN_NAME: app.calculated.fi
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
