name: Run Tests

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
        required: true
        description: Github environment to use
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      AWS_REGION:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      NEXT_PUBLIC_CHAIN_ID:
        required: true
      NEXT_PUBLIC_CONTRACT_ADDRESS:
        required: true
      NEXT_PUBLIC_REST_ENDPOINT:
        required: true
      NEXT_PUBLIC_RPC_ENDPOINT:
        required: true
      NEXT_PUBLIC_STAKING_ROUTER_CONTRACT_ADDRESS:
        required: true
      NEXT_PUBLIC_FEE_TAKER_ADDRESS:
        required: true
      NEXT_PUBLIC_HOTJAR_SITE_ID:
        required: true
  pull_request:
    inputs:
      ENVIRONMENT:
        type: string
        required: true
        description: Github environment to use
        default: test

jobs:
  set-env:
    name: Set Environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - id: set-env
        run: |
          ENVIRONMENT=${{ inputs.ENVIRONMENT }}
          echo "::set-output name=environment::${ENVIRONMENT:-"test"}"

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: set-env
    environment: ${{ needs.set-env.outputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      NEXT_PUBLIC_CHAIN_ID: ${{ secrets.NEXT_PUBLIC_CHAIN_ID }}
      NEXT_PUBLIC_CONTRACT_ADDRESS: ${{ secrets.NEXT_PUBLIC_CONTRACT_ADDRESS }}
      NEXT_PUBLIC_REST_ENDPOINT: ${{ secrets.NEXT_PUBLIC_REST_ENDPOINT }}
      NEXT_PUBLIC_RPC_ENDPOINT: ${{ secrets.NEXT_PUBLIC_RPC_ENDPOINT }}
      NEXT_PUBLIC_STAKING_ROUTER_CONTRACT_ADDRESS: ${{ secrets.NEXT_PUBLIC_STAKING_ROUTER_CONTRACT_ADDRESS }}
      NEXT_PUBLIC_FEE_TAKER_ADDRESS: ${{ secrets.NEXT_PUBLIC_FEE_TAKER_ADDRESS }}
      NEXT_PUBLIC_HOTJAR_SITE_ID: ${{ secrets.NEXT_PUBLIC_HOTJAR_SITE_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install Dependencies
        run: yarn install

      - name: Run Lint
        run: yarn lint

      - name: Run Typecheck
        run: yarn typecheck

      - name: Run Tests
        run: yarn test
