name: 'Deploy: Reusable'

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
        required: true
        description: Github environment to use
      BUCKET_DOMAIN_NAME:
        type: string
        required: true
        description: Domain name used for bucket name

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      AWS_REGION:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      NEXT_PUBLIC_CHAIN_ID:
        required: true
      NEXT_PUBLIC_CONTRACT_ADDRESS:
        required: true
      NEXT_PUBLIC_REST_ENDPOINT:
        required: true
      NEXT_PUBLIC_RPC_ENDPOINT:
        required: true
      NEXT_PUBLIC_STAKING_ROUTER_CONTRACT_ADDRESS:
        required: true
      NEXT_PUBLIC_FEE_TAKER_ADDRESS:
        required: true
      NEXT_PUBLIC_HOTJAR_SITE_ID:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Infrastructure
    environment: ${{ inputs.ENVIRONMENT }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      NEXT_PUBLIC_CHAIN_ID: ${{ secrets.NEXT_PUBLIC_CHAIN_ID }}
      NEXT_PUBLIC_CONTRACT_ADDRESS: ${{ secrets.NEXT_PUBLIC_CONTRACT_ADDRESS }}
      NEXT_PUBLIC_REST_ENDPOINT: ${{ secrets.NEXT_PUBLIC_REST_ENDPOINT }}
      NEXT_PUBLIC_RPC_ENDPOINT: ${{ secrets.NEXT_PUBLIC_RPC_ENDPOINT }}
      NEXT_PUBLIC_STAKING_ROUTER_CONTRACT_ADDRESS: ${{ secrets.NEXT_PUBLIC_STAKING_ROUTER_CONTRACT_ADDRESS }}
      NEXT_PUBLIC_FEE_TAKER_ADDRESS: ${{ secrets.NEXT_PUBLIC_FEE_TAKER_ADDRESS }}
      NEXT_PUBLIC_HOTJAR_SITE_ID: ${{ secrets.NEXT_PUBLIC_HOTJAR_SITE_ID }}

      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      BUCKET_DOMAIN_NAME: ${{ inputs.BUCKET_DOMAIN_NAME }}
      PROJECT_NAME: calc
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install Dependencies
        run: yarn install

      - name: Copy Environment Config Files
        working-directory: ./infrastructure
        run: cp -r ./${{ inputs.ENVIRONMENT }}/* ./

      - name: Build App
        run: yarn build

      - name: Export App
        run: yarn export

      - name: inject sentry test ids
        run: yarn sentry sourcemaps inject out

      - name: upload sourcemaps to sentry
        run: yarn sentry sourcemaps inject out
